version: '3.8'

services:
  # Redis for onix-bap-plugin
  redis-onix-bap:
    image: redis:alpine
    container_name: redis-onix-bap
    ports:
      - "6379:6379"
    networks:
      - onix-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # Redis for onix-bpp-plugin
  redis-onix-bpp:
    image: redis:alpine
    container_name: redis-onix-bpp
    ports:
      - "6380:6379"
    networks:
      - onix-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # Onix BAP Plugin
  onix-bap-plugin:
    image: manendrapalsingh/onix-bap-plugin:latest
    container_name: onix-bap-plugin
    ports:
      - "8001:8001"
    volumes:
      # Mount config directory (writable for symlink creation, but original files won't be modified)
      - ../../../../docker/monolithic/api/config/onix-bap:/app/config/onix-bap
      # Mount adapter.yaml directly to expected location
      - ../../../../docker/monolithic/api/config/onix-bap/adapter.yaml:/app/config/adapter.yaml:ro
      # Mount schema directory (read-only)
      - ../../../../schemas:/app/schemas:ro
    environment:
      - CONFIG_FILE=/app/config/adapter.yaml
    restart: unless-stopped
    depends_on:
      redis-onix-bap:
        condition: service_healthy
      mock-registry:
        condition: service_healthy
    networks:
      - onix-network

  # Onix BPP Plugin
  onix-bpp-plugin:
    image: manendrapalsingh/onix-bpp-plugin:latest
    container_name: onix-bpp-plugin
    ports:
      - "8002:8002"
    volumes:
      # Mount config directory (writable for symlink creation, but original files won't be modified)
      - ../../../../docker/monolithic/api/config/onix-bpp:/app/config/onix-bpp
      # Mount adapter.yaml directly to expected location
      - ../../../../docker/monolithic/api/config/onix-bpp/adapter.yaml:/app/config/adapter.yaml:ro
      # Mount schema directory (read-only)
      - ../../../../schemas:/app/schemas:ro
    environment:
      - CONFIG_FILE=/app/config/adapter.yaml
    restart: unless-stopped
    depends_on:
      redis-onix-bpp:
        condition: service_healthy
      mock-registry:
        condition: service_healthy
    networks:
      - onix-network

  # Mock CDS Service
  mock-cds:
    image: manendrapalsingh/mock-cds:latest
    container_name: mock-cds
    ports:
      - "8082:8082"
    volumes:
      # Mount config file from local directory
      - ./mock-cds_config.yml:/app/config/config.yaml:ro
    environment:
      # Optional: Override config file path if needed
      # CONFIG_FILE: /app/config/config.yaml
    networks:
      - onix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      mock-registry:
        condition: service_healthy

  # Mock Registry Service
  mock-registry:
    image: manendrapalsingh/mock-registry:latest
    container_name: mock-registry
    ports:
      - "3030:3030"
    volumes:
      # Mount config file from local directory
      - ./mock-registry_config.yml:/app/config/config.yaml:ro
    environment:
      # Optional: Override config path if mounted at different location
      # - CONFIG_PATH=/app/config/config.yaml
    networks:
      - onix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Mock BAP Service
  mock-bap:
    image: manendrapalsingh/mock-bap:latest
    container_name: mock-bap
    ports:
      - "9001:9001"
    volumes:
      # Mount config file from local directory
      - ./mock-bap_config.yml:/app/config/config.yaml:ro
    environment:
      # Optional: Override config file path if needed
      # CONFIG_FILE: /app/config/config.yaml
    networks:
      - onix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Mock BPP Service
  mock-bpp:
    image: manendrapalsingh/mock-bpp:latest
    container_name: mock-bpp
    ports:
      - "9002:9002"
    volumes:
      # Mount config file from local directory
      - ./mock-bpp_config.yml:/app/config/config.yaml:ro
    environment:
      # Optional: Override config file path if needed
      # CONFIG_FILE: /app/config/config.yaml
    networks:
      - onix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  onix-network:
    driver: bridge

