appName: "onix-ev-charging"

log:
  level: debug
  destinations:
    - type: stdout
  contextKeys:
    - transaction_id
    - message_id
    - subscriber_id
    - module_id

http:
  port: 8001
  timeout:
    read: 30
    write: 30
    idle: 30

pluginManager:
  root: /app/plugins

modules:
  # BAP Receiver - Receives callbacks from CDS (Phase 1) and BPPs (Phase 2+)
  # Phase 1: Receives on_search from CDS with aggregated catalog
  # Phase 2+: Receives callbacks from BPPs (on_select, on_init, on_confirm, etc.)
  - name: bapTxnReceiver
    path: /bap/receiver/
    handler:
      type: std
      role: bap
      httpClientConfig:
        maxIdleConns: 1000
        maxIdleConnsPerHost: 200
        idleConnTimeout: 300s
        responseHeaderTimeout: 5s
      plugins:
        registry:
          id: registry
          config:
            url: http://mock-registry:3030
            retry_max: 3
            retry_wait_min: 100ms
            retry_wait_max: 500ms
        keyManager:
          id: simplekeymanager
          config:
            networkParticipant: example-bap.com
            keyId: bap-key-1
            signingPrivateKey: xnKF3BIg3Ei+ZEvxBtK0Mm4GRG1Mr0+K9IrxT6CnHEE=
            signingPublicKey: MKA6fln8vmU2Qn80Y7dLzagpaPNqQWOlvGglMo5s0IU=
            encrPrivateKey: xnKF3BIg3Ei+ZEvxBtK0Mm4GRG1Mr0+K9IrxT6CnHEE=
            encrPublicKey: MKA6fln8vmU2Qn80Y7dLzagpaPNqQWOlvGglMo5s0IU=
        cache:
          id: cache
          config:
            addr: redis-onix-bap:6379
        schemaValidator:
          id: schemavalidator
          config:
            schemaDir: /app/schemas
        signValidator:
          id: signvalidator
        router:
          id: router
          config:
            routingConfig: /app/config/onix-bap/bap_receiver_routing.yaml
        middleware:
          - id: reqpreprocessor
            config:
              uuidKeys: transaction_id,message_id
              role: bap
      steps:
        - validateSign
        - addRoute
        - validateSchema

  # BAP Caller - Entry point for all requests from BAP
  # Phase 1: Routes search to external CDS for aggregation
  # Phase 2+: Routes other requests directly to BPP (bypasses CDS)
  # Uses bpp_uri from context for dynamic routing in Phase 2+
  - name: bapTxnCaller
    path: /bap/caller/
    handler:
      type: std
      role: bap
      httpClientConfig:
        maxIdleConns: 1000
        maxIdleConnsPerHost: 200
        idleConnTimeout: 300s
        responseHeaderTimeout: 5s
      plugins:
        registry:
          id: registry
          config:
            url: http://mock-registry:3030
            retry_max: 3
            retry_wait_min: 100ms
            retry_wait_max: 500ms
        keyManager:
          id: simplekeymanager
          config:
            networkParticipant: example-bap.com
            keyId: bap-key-1
            signingPrivateKey: xnKF3BIg3Ei+ZEvxBtK0Mm4GRG1Mr0+K9IrxT6CnHEE=
            signingPublicKey: MKA6fln8vmU2Qn80Y7dLzagpaPNqQWOlvGglMo5s0IU=
            encrPrivateKey: xnKF3BIg3Ei+ZEvxBtK0Mm4GRG1Mr0+K9IrxT6CnHEE=
            encrPublicKey: MKA6fln8vmU2Qn80Y7dLzagpaPNqQWOlvGglMo5s0IU=
        cache:
          id: cache
          config:
            addr: redis-onix-bap:6379
        router:
          id: router
          config:
            routingConfig: /app/config/onix-bap/bap_caller_routing.yaml
        signer:
          id: signer
        middleware:
          - id: reqpreprocessor
            config:
              uuidKeys: transaction_id,message_id
              role: bap
      steps:
        - addRoute
        - sign

plugins:
  - registry
  - simplekeymanager
  - cache
  - schemavalidator
  - signvalidator
  - router
  - signer
  - reqpreprocessor

