# ONIX BAP Caller Routing Configuration

# Supports Phase 1 (Discover Aggregation) and Phase 2+ (Direct BPP Routing)
# Phase 1: Discover (Aggregation via CDS)
# Phase 2+: Other Requests (Direct to BPP, NO CDS involvement)
# These routes use bpp_uri from context (provided in on_discover aggregated response)

routingRules:
  # Phase 1: Discover to CDS
  - domain: ev_charging_network
    version: "1.0.0"
    targetType: url
    target:
      url: http://mock-cds:8082/csd
      excludeAction: false
    endpoints:
      - discover

  # Phase 2+: Other actions to BPP (via context_endpoint)
  - domain: ev_charging_network
    version: "1.0.0"
    targetType: bpp
    target: {}
    endpoints:
      - select
      - init
      - confirm
      - status
      - track
      - cancel
      - update
      - rating
      - support

