version: '3.8'

services:
  mock-bap:
    image: manendrapalsingh/mock-bap:latest
    container_name: mock-bap
    ports:
      - "9001:9001"
    volumes:
      # Mount config file from local directory
      - ./config.yaml:/app/config/config.yaml:ro
    environment:
      # Optional: Override config file path if needed
      # CONFIG_FILE: /app/config/config.yaml
    networks:
      - mock-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  mock-network:
    driver: bridge

